version: '3.9'

services:
  postgres:
    ports:
      - 5432:5432

  booking_api:
    # ports:
    #   - 8080:8080
    expose:
      - 8080

  mock_movie_api:
    ports:
      - 8082:8082

  mock_auth:
    ports:
      - 8081:8081

  mock_ugc:
    ports:
      - 8083:8083

  url_shortener:
    ports:
      - "3000:3000"

  redis:
    ports:
      - 6379:6379

  booking_review_api:
    # ports:
    #   - 8084:8084
    expose:
      - 8084
