version: '3.9'

services:
  test:
    container_name: test_booking
    build:
      context: backend/Booking/booking_api
      dockerfile: test.Dockerfile
    env_file:
      - .env
    networks:
      - project-network

networks:
  project-network:
    external: true
