version: '3.9'

services:
  postgres:
    ports:
      - 5432:5432

  booking_api:
    # ports:
    #   - 8080:8080
    expose:
      - 8080

  mock_movie_api:
    ports:
      - 8082:8082

  mock_auth:
    ports:
      - 8081:8081
