@startuml layers
' !theme materia
autonumber
skinparam sequence {
    ParticipantPadding 20
    MessageAlign center
}

title GET '/booking/{booking_id}'

participant Client as Client
participant "Booking API" as API
participant "BookingService" as Service
participant "BookingRepository" as BookingRepo
participant "AnnounceRepository" as AnnounceRepo
participant "UserRepository" as UserRepo
participant "MovieRepository" as MovieRepo
participant "RatingRepository" as RatingRepo
database "Cache" as Cache_Service
database "Booking DB" as DB_Booking
participant DB_Booking
participant Auth
participant Movie_API
participant Rating


Client -> API: - Booking_id
API -> API:
note right
    - проверка access_headers
end note
API -> Service: - user\n - Booking_id

group Booking Service

    group #C9B2E9 layer_service
        Service -> Service
        note right
            - self.repo.get_bi_id()
        end note
        end group

        Service --> BookingRepo: - Booking_id

        group #C9B2E9 layer_repo
            BookingRepo -> BookingRepo
            note right
                - create query
            end note

            BookingRepo -> BookingRepo
            note right
                - self.db.execute()
            end note

            BookingRepo --> DB_Booking: Select Booking(id)
            DB_Booking -> BookingRepo: - layer_models.PGBooking
            end group

            BookingRepo -> Service: - layer_models.PGBooking

            group #C9B2E9 layer_service
            Service -> Service
                note right
                    - self._check_permissions()
                end note
                Service -> Service
                note right
                    - self.announce_repo.get_by_id()
                end note
                end group

                Service --> AnnounceRepo: - Announcement_id

                group #C9B2E9 layer_repo
                    AnnounceRepo -> AnnounceRepo
                    note right
                        - create query
                    end note

                    AnnounceRepo -> AnnounceRepo
                    note right
                        - self.db.execute()
                    end note

                    AnnounceRepo --> DB_Booking: Select Announcement(id)
                    DB_Booking -> AnnounceRepo: - layer_models.PGAnnouncement
                    end group

                    AnnounceRepo -> Service: layer_models.AnnounceToResponse

                    group #C9B2E9 layer_service
                        Service -> Service
                        note right
                            - self.user_repo.get_by_id()
                        end note
                        end group

                        Service --> UserRepo: - author_id

                        group #C9B2E9 layer_repo
                            UserRepo -> Cache_Service: get_from_cache
                            Cache_Service -> UserRepo: layer_models.UserToResponse

                            group alt
                                UserRepo -> Auth: - author_id
                                Auth -> UserRepo: - layer_models.UserToResponse
                                UserRepo -> Cache_Service: set_to_cache
                                end group
                                end group

                                UserRepo -> Service: - layer_models.UserToResponse

                                group #C9B2E9 layer_service
                                    Service -> Service
                                    note right
                                        - self.movie_repo.get_by_id()
                                    end note
                                    end group

                                    Service --> MovieRepo: - movie_id

                                    group #C9B2E9 layer_repo
                                        MovieRepo -> Cache_Service: get_from_cache
                                        Cache_Service -> MovieRepo: layer_models.MovieToResponse
                                        group alt
                                            MovieRepo -> Movie_API: - movie_id
                                            Movie_API -> MovieRepo: - layer_models.MovieToResponse
                                            MovieRepo -> Cache_Service: set_to_cache
                                            end group
                                            end group

                                            MovieRepo -> Service: - layer_models.MovieToResponse

                                            group #C9B2E9 layer_service
                                                Service -> Service
                                                note right
                                                    - self.rating_repo.get_by_id()
                                                end note
                                                end group

                                                Service --> RatingRepo: - author_id

                                                group #C9B2E9 layer_repo
                                                    RatingRepo -> Cache_Service: get_from_cache
                                                    Cache_Service -> RatingRepo: layer_models.RatingToResponse
                                                    group alt
                                                        RatingRepo -> Rating: - author_id
                                                        Rating -> RatingRepo: - layer_models.RatingToResponse
                                                        RatingRepo -> Cache_Service: set_to_cache
                                                        end group
                                                        end group

                                                        RatingRepo -> Service: - layer_models.RatingToResponse

                                                        group #C9B2E9 layer_service
                                                            Service -> Service
                                                            note right
                                                                - create Response
                                                            end note

                                                            end group
                                                            end group

                                                            Service -> API: - layer_models.DetailBookingResponse

                                                            API -> Client: - layer_models.DetailBookingResponse
                                                            @enduml