version: '3.9'

services:
  admin-panel:
    ports:
      - 8000:8000
    expose:
      - 8000

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  notification_api:
    # ports:
    #   - 8070:8070
    expose:
      - 8070
