@startuml layers
' !theme materia
autonumber
skinparam sequence {
    ParticipantPadding 20
    MessageAlign center
}

title DELETE '/announcement/{announcement_id}'

participant Client as Client
participant "Booking API" as API
participant "AnnouncementService" as Service
participant "AnnounceRepository" as AnnounceRepo
participant "BookingRepository" as BookingRepo
participant "UserRepository" as UserRepo
participant "MovieRepository" as MovieRepo
participant "RatingRepository" as RatingRepo
database "Cache" as Cache_Service
database "Booking DB" as DB_Booking


Client -> API: - announce_id
API -> API:
note right
    - проверка access_headers
end note
API -> Service: - user\n - announce_id

group Announcement Service

    group #B2C7E8 layer_service

        Service -> Service
        note right
            - self._check_permissions()
        end note

        Service -> Service
        note right
            - self.repo.get_bi_id()
        end note
        end group

        Service --> AnnounceRepo: - Announcement_id

        group #B1C7E8 layer_repo
            AnnounceRepo -> AnnounceRepo
            note right
                - create query
            end note

            AnnounceRepo -> AnnounceRepo
            note right
                - self.db.execute()
            end note

            AnnounceRepo -> DB_Booking: Select Announcement(id)
            DB_Booking -> AnnounceRepo: - layer_models.PGAnnouncement
            end group
            AnnounceRepo -> Service: - layer_models.PGAnnouncement

            group #B2C7E8 layer_service
                Service -> Service
                note right
                    - row check
                end note
                Service -> Service
                note right
                    - self.repo.delete()
                end note
                end group

                Service --> AnnounceRepo: - announce_id
                group #B1C7E8 layer_repo

                    AnnounceRepo -> AnnounceRepo
                    note right
                        - create query
                    end note

                    AnnounceRepo -> AnnounceRepo
                    note right
                        - self.db.execute()
                    end note

                    AnnounceRepo --> DB_Booking: Delete announce_id
                    end group

                    group #B1C7E8 layer_service
                        Service -> Service
                        note right
                            - create payload
                        end note
                        Service -> Service
                        note right
                            - self.notific_repo.send()
                        end note
                        end group
                        Service -> Notification: - layer_models.Event
                        group #B1C7E8 layer_repo
                            Notification -> Notification
                            note right
                                - create Notific
                            end note
                            Notification -> Notification
                            note right
                                - send Notific
                            end note

                            end group
                            end group

                            Service -> API: - HTTPStatus

                            API -> Client: - HTTPStatus
                            @enduml